### PR TITLE
Fixed double subscribe issue

### PR DESCRIPTION
**Pull request by Bananahavoc**
This is a quick fix for an issue where subscriptions made in the OnAuthentication callback ended up being subscribed to twice. A better fix would be to make socketclustedclient only re-subscribe to channels based on their state.

### CODE REVIEW

**Comment by sacOO7** [comment]
HI @BananaHemic , I am not getting the exact problem. Can you elaborate in more detailed format? In the PR, I can only see channel subscribe getting called after onAuthentication callback, which was previously before the callback.

**Comment by sacOO7** [comment]
HI @BananaHemic , I am not getting the exact problem. Can you elaborate in more detailed format? In the PR, I can only see channel subscribe getting called before onAuthentication callback, which was previously after the callback.

**Comment by Bananahavoc** [comment]
Sure, the issue here is that the subscribing to a channel ends up happening twice.

In the on authentication callback I am subscribing to a channel. This works, but immediately after the on authentication callback is fired, the self.subscribechannels() line hits, and the channel is re-subscribed to. 

A better solution than the one in my PR would be to not resend the subscription request if the channel is subscribed to (I think the javascript socketcluster client does this, but I'm not certain).

If that still doesn't make sense, let me know and I can attach an example script.

**Comment by sacOO7** [comment]
Hi @BananaHemic, was able to reproduce the issue, will be merging your PR. Thank you for your help :+1:

**Comment by sacOO7** [comment]
Hi @BananaHemic , I have merged your PR. Please install latest version of client and let me know if you face any further issues 👍

**Pull request merged**
